POST https://api-node-sscc.onrender.com
Content-type: application/json

{
    "title": "Vídeo node",
    "description": "Primeiro vídeo",
    "duration": 100
}

###

GET https://api-node-sscc.onrender.com
//Search é opcional e com a função em database-memory retorna apenas vídeos onde o título inclui a palavra pesquisada, isso é Query-parameters

###

PUT https://api-node-sscc.onrender.com/a6827ecb-6ecd-4eb0-9a44-9e8068ed4ab2
Content-type: application/json

{
    "title": "Vídeo 02",
    "description": "Primeiro vídeo",
    "duration": 100
}

###

DELETE https://api-node-sscc.onrender.com/a6827ecb-6ecd-4eb0-9a44-9e8068ed4ab2




